version: '2'
<<<<<<< HEAD
services:
  website:
    build: .
    ports:
      - '4200:4200'
    volumes:
      - '.:/onebnb_client'
=======
 
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
 
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
 
  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/onebnb_api'
    env_file:
      - '.env'
 
  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/onebnb_api'
    env_file:
      - '.env'
 
volumes:
  redis:
  postgres:
>>>>>>> a50ef2c44078729a238abd9a7f1c9ae193bf4386
